# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [82]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [83]:
#a = 
a = pd.Series([100,200,300,400])

Print a, and data type

In [84]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [85]:
a[2]

np.int64(300)

What are the values of index for series a?

In [86]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [87]:
a.index = ['c','a','b','d']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [88]:


a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [89]:

print(a. sort_index())

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [90]:
# b = 
b = pd.Series([800,450,100],index =['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [91]:
# a =
a= pd.concat([a,b])
print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

In [92]:
#print a again after appending b into it


print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [93]:
# a = 

a.sort_index(ascending = False)

g    100
f    450
e    800
d    400
c    100
b    300
a    200
dtype: int64

In [94]:

print(a.index)

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [95]:
# df = 

df = pd.DataFrame(a)

In [96]:
print(df)

     0
c  100
a  200
b  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [97]:

print(df.shape)

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [98]:
# yep its same as the series.
print((df.index),a)

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='object') c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [99]:
print(df.head(5))

#head represent to dataframes first 5 rows

     0
c  100
a  200
b  300
d  400
e  800

In [100]:
print(df.tail(5))

#tail represent to dataframes last 5 rows

     0
b  300
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [101]:


df.columns=['points']
print(df)

   points
c     100
a     200
b     300
d     400
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [102]:
#Create fruits array

 #fruits =

fruits =pd.Series( ['orange','mango','apple','apple','mango','orange','mango'])
print(fruits)

0    orange
1     mango
2     apple
3     apple
4     mango
5    orange
6     mango
dtype: object

In [103]:
#Create series fruits out of fruits array

# fruits =

fruits =pd.Series(fruits)

Change the index of fruits to the index of dataframe df

In [104]:


df=pd.DataFrame(fruits)
print(df)

        0
0  orange
1   mango
2   apple
3   apple
4   mango
5  orange
6   mango

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [105]:

df['fruits'] = fruits

In [106]:

print(df.head())

        0  fruits
0  orange  orange
1   mango   mango
2   apple   apple
3   apple   apple
4   mango   mango

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [196]:
# d1 = 

d1 = pd.DataFrame({'city':['Chandigarh','Delhi','Kanpur','Chennai','Manali'],'Temperature': [15,22,20,26,-2]})

Print(d1)

In [197]:

print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [198]:


d1.shape

(5, 2)

Set city = d1['city']

In [199]:


city = d1['city']

print city <br>
What is the type of city.

In [200]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another dataframe 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [201]:
# d2 = 

d2 = pd.DataFrame({'city':['Bengalaru','Coimbatore','Srirangam','Pondicherry'],'Temperature':[24,35,36,39]})

print the shape of this dataframe

In [202]:

print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [203]:
# d3 = 

d3 =pd.concat([d1,d2])
print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [204]:
print(d2[d2['Temperature'] <=20])

Empty DataFrame
Columns: [city, Temperature]
Index: []

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [205]:

print(d2[d2['Temperature'] >=35])

          city  Temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [214]:
# write function here


d3['is_UT']=d3['city'].isin(['Chandigarh','Pondicherry','Delhi'])

def is_ut(x):
     return x in['Chandigarh','Pondicherry','Delhi']

     d3['is_ut']=d3['city'].apply(is_ut)

In [215]:
# print d3
print(d3)

          city  Temperature  is_UT
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [250]:
# write function here


def c_to_f(x):
    return (x * 8/6) + 37

In [251]:
# check function c_to_f(10)


print(c_to_f(10))

50.333333333333336

In [252]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'


d3['Temprature_f'] = d3['Temperature'].apply(c_tof)
d3

          city  Temperature  is_UT  Temprature_f
0   Chandigarh           15   True          59.0
1        Delhi           22   True          71.6
2       Kanpur           20  False          68.0
3      Chennai           26  False          78.8
4       Manali           -2  False          28.4
0    Bengalaru           24  False          75.2
1   Coimbatore           35  False          95.0
2    Srirangam           36  False          96.8
3  Pondicherry           39   True         102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [253]:
d1['is_UT'] = d1['city'].isin(['Chandigarh','Pondicherry','Delhi'])
result = d1[d1['is_UT']]
print(result)

         city  Temperature  is_UT
0  Chandigarh           15   True
1       Delhi           22   True

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [257]:

print(d1[d1['Temperature'] > 90])

Empty DataFrame
Columns: [city, Temperature, is_UT]
Index: []

Select only the first three rows of the dataframe d1.

In [258]:
d1.head(3)

         city  Temperature  is_UT
0  Chandigarh           15   True
1       Delhi           22   True
2      Kanpur           20  False

Select all the rows and last two columns in the dataframe.

In [261]:
d1.iloc[:,-2:]

   Temperature  is_UT
0           15   True
1           22   True
2           20  False
3           26  False
4           -2  False

## Groupby

In [263]:
# Create a dataframe using dictionary of your choice

# data = 

data = {
    'Name':['vinoth','Mohan','Ram'],
    'Age':[18,28,25],
    'City':['Delhi','Mumbai','Chennai']
}

df = pd.DataFrame(data)
print(df)

     Name  Age     City
0  vinoth   18    Delhi
1   Mohan   28   Mumbai
2     Ram   25  Chennai

In [267]:
# Use Groupby of single column with aggregate sum()


df.groupby('Name').sum()

        Age     City
Name
Mohan    28   Mumbai
Ram      25  Chennai
vinoth   18    Delhi

In [269]:
# Use Groupby of single column with aggregate count()

df.groupby('Name').count()

        Age  City
Name
Mohan     1     1
Ram       1     1
vinoth    1     1

In [273]:
# Use Groupby of single column with aggregate min() and max()


df.groupby('Name').agg(['min','max'])

       Age         City
       min max      min      max
Name
Mohan   28  28   Mumbai   Mumbai
Ram     25  25  Chennai  Chennai
vinoth  18  18    Delhi    Delhi

In [279]:
# Use Groupby of any 2 columns with aggregate mean()

df.groupby(['Name','City']).mean()

                 Age
Name   City
Mohan  Mumbai   28.0
Ram    Chennai  25.0
vinoth Delhi    18.0

In [280]:
# Use Groupby of any 2 columns with aggregate min() and max()


df.groupby(['Name','City']).agg(['min','max'])

               Age
               min max
Name   City
Mohan  Mumbai   28  28
Ram    Chennai  25  25
vinoth Delhi    18  18

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [288]:
# a = 
a =pd.date_range (start= '01-01-2020',end ='01-04-2021')

print a

In [289]:

print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-12-26', '2020-12-27', '2020-12-28', '2020-12-29',
               '2020-12-30', '2020-12-31', '2021-01-01', '2021-01-02',
               '2021-01-03', '2021-01-04'],
              dtype='datetime64[ns]', length=370, freq='D')

What is the len of a?

In [290]:

print(len(a))

370

What is the type of a?

In [291]:


print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>